   adb shell pm uninstall -k --user 0 com.heytap.browser
   adb shell pm uninstall -k --user 0 com.heytap.browser
#   adb shell pm uninstall -k --user 0 com.google.android.apps.googleassistant
#   adb shell pm uninstall -k --user 0 com.coloros.calculator
   adb shell pm uninstall -k --user 0 com.coloros.backuprestore
   adb shell pm uninstall -k --user 0 com.coloros.backuprestore.remoteservice
   adb shell pm uninstall -k --user 0 com.coloros.backuprestore.remoteservice
   adb shell pm uninstall -k --user 0 com.coloros.video
   adb shell pm uninstall -k --user 0 com.coloros.weather.service
   adb shell pm uninstall -k --user 0 com.weather2
   adb shell pm uninstall -k --user 0 com.coloros.weather2
   adb shell pm uninstall -k --user 0 com.coloros.widget.smallweather
   adb shell pm uninstall -k --user 0 com.google.android.apps.podcasts
   adb shell pm uninstall -k --user 0 com.google.android.youtube
   adb shell pm uninstall -k --user 0 com.coloros.gamespace
   adb shell pm uninstall -k --user 0 com.coloros.gamespaceui
   adb shell pm uninstall -k --user 0 com.heytap.themestore
   adb shell pm uninstall -k --user 0 com.heytap.cloud
   adb shell pm uninstall -k --user 0 com.facebook.appmanager
   adb shell pm uninstall -k --user 0 com.coloros.phonemanager
   adb shell pm uninstall -k --user 0 com.oppo.music
   adb shell pm uninstall -k --user 0 com.coloros.gallery3d
   adb shell pm uninstall -k --user 0 com.google.android.videos
#   adb shell pm uninstall -k --user 0 com.google.android.apps.maps
   adb shell pm uninstall -k --user 0 com.coloros.securepay
   adb shell pm uninstall -k --user 0 com.google.android.apps.nbu.paisa.user
   adb shell pm uninstall -k --user 0 com.heytap.themestore
   adb shell pm uninstall -k --user 0 com.google.android.gm
   adb shell pm uninstall -k --user 0 com.google.android.apps.messaging
   adb shell pm uninstall -k --user 0 com.coloros.providers.downloads.ui
   adb shell pm uninstall -k --user 0 com.dropboxchmod
   adb shell pm uninstall -k --user 0 com.heytap.themestore
   adb shell pm uninstall -k --user 0 com.heytap.pictorial
   adb shell pm uninstall -k --user 0 com.heytap.usercenter.overlay
   adb shell pm uninstall -k --user 0 com.heytap.usercenter
   adb shell pm uninstall -k --user 0 com.coloros.securepay
#   adb shell pm uninstall -k --user 0 com.android.chrome
   adb shell pm uninstall -k --user 0 com.heytap.habit.analysis
   adb shell pm uninstall -k --user 0 com.heytap.market
   adb shell pm uninstall -k --user 0 com.heytap.openid
   adb shell pm uninstall -k --user 0 com.heytap.mcs
   adb shell pm uninstall -k --user 0 com.heytap.usercenter
   adb shell pm uninstall -k --user 0 com.nearme.atlas
   adb shell pm uninstall -k --user 0 com.nearme.statistics.rom
   adb shell pm uninstall -k --user 0 com.oppo.atlas
   adb shell pm uninstall -k --user 0 com.oppo.criticallog
   adb shell pm uninstall -k --user 0 com.oppo.operationManual
   adb shell pm uninstall -k --user 0 com.oppo.partnerbrowsercustomizations
   adb shell pm uninstall -k --user 0 com.oppo.quicksearchbox
   adb shell pm uninstall -k --user 0 com.oppo.logkit
   adb shell pm uninstall -k --user 0 com.oppo.qualityprotect
   adb shell pm uninstall -k --user 0 com.oppoex.afterservice
   adb shell pm uninstall -k --user 0 com.realme.securitycheck
   adb shell pm uninstall -k --user 0 com.redteamobile.roaming
   adb shell pm uninstall -k --user 0 com.redteamobile.roaming.deamon
   adb shell pm uninstall -k --user 0 com.ted.number
   adb shell pm uninstall -k --user 0 com.tencent.soter.soterserver
   adb shell pm uninstall -k --user 0 com.google.android.projection.gearhead
